default: &default
  adapter:  postgresql
  host:     localhost
  pool: 5
  timeout: 5000
  encoding: UTF8
  username: postgres
  password: admin

development:
  <<: *default
  database: angular_casts_development

test:
  <<: *default
  database: angular_casts_test

production:
  <<: *default
  database: angular_casts_production


